# Generated by Django 3.2.13 on 2022-06-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='salary',
        ),
    ]
