# Generated by Django 3.2.13 on 2022-07-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
