# Generated by Django 3.2.13 on 2022-06-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_coverletter_submited_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='submited_letter',
        ),
    ]
