# Generated by Django 3.2.13 on 2022-06-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_coverletter_submited_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='full_name',
        ),
    ]
