# Generated by Django 3.2.13 on 2022-07-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20220720_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='coverletter',
            name='postition_type',
        ),
    ]
