# Generated by Django 3.2.13 on 2022-06-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_coverletter_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joblisting'),
        ),
    ]
