# Generated by Django 3.2.13 on 2022-06-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_coverletter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
