# Generated by Django 3.2.13 on 2022-06-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20220621_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
