# Generated by Django 3.2.13 on 2022-06-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_joblisting_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='employer',
            field=models.CharField(max_length=200),
        ),
    ]
