# Generated by Django 3.2.13 on 2022-06-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_alter_joblisting_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='employer',
        ),
    ]
